title: "Lionel Messi FC"
email: lionelmessi.help@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/ur-cristiano-logo.png'
favicon: 'assets/images/favicon.ico'
author: IshowSpeed
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  ishowspeed:
    name: IshowSpeed
    display_name: IshowSpeed
    avatar: 'assets/images/Author-Messi.webp'
    email: lionelmessi.help@gmail.com
    web: https://messi-lionel.github.io
    twitter: https://x.com/LionelMessi
    description: "Hi, I am the author of this article. Lionel Messi is widely regarded as one of the greatest footballers of all time. This site is dedicated to providing the latest updates, stats, and lifestyle insights about Messi."
 
# Social
social:
  instagram: https://www.instagram.com/ishowspeed
  facebook: https://www.facebook.com/Ishowspeed/
  twitter: https://x.com/IshowSpeedSui

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives